services:
  - type: web
    name: backend
    env: docker
    region: oregon
    plan: free
    rootDir: modulo 2/backend
    buildCommand: docker build -t backend .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snake-db
          property: connectionString

  - type: web
    name: frontend
    env: docker
    region: oregon
    plan: free
    rootDir: modulo 2/frontend
    buildCommand: docker build -t frontend .
    envVars:
      - key: BACKEND_HOST
        fromService:
          type: web
          name: backend
          property: hostport

databases:
  - name: snake-db
    region: oregon
    plan: free
    databaseName: snake_db
    user: user

version: "1"
