services:
  - type: web
    name: homework-module-2
    env: docker
    region: oregon
    plan: free
    rootDir: homework_module_2
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000

version: "1"
