services:
  - type: web
    name: backend
    env: docker
    region: oregon
    plan: free
    rootDir: modulo 2/backend
    buildCommand: docker build -t backend .
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snake-db
          property: connectionString
      - key: PORT
        value: 10000

  - type: web
    name: frontend
    env: docker
    region: oregon
    plan: free
    rootDir: modulo 2/frontend
    buildCommand: docker build -t frontend .
    startCommand: ./entrypoint.sh
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: backend
          property: url

databases:
  - name: snake-db
    region: oregon
    plan: free
    databaseName: snake_db
    user: user

version: "1"
